- name: install system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git-core
    - curl
    - wget
    - libpq-dev
    - build-essential
    - python-software-properties
    - python-mysqldb